export const STORE_USERID = 'STORE_USERID';
export const STORE_LABEL_CONTENT = 'STORE_LABEL_CONTENT';
export const NOTE_KEYS = 'NOTE_KEYS';
export const STORE_LABELS = 'STORE_LABELS';
export const SHOW_DELETE_DAILOG = 'SHOW_DELETE_DAILOG';
export const DELETE_LABEL_KEY = 'DELETE_LABEL_KEY';
export const SELECTED_LABEL_KEY = 'SELECTED_LABEL_KEY';
export const NOTES_ARCHIVED = 'NOTES_ARCHIVED';
export const EDIT_NOTES_DETAILS = 'EDIT_NOTES_DETAILS';
export const NOTEKEY_TO_ADD_NOTE = 'NOTEKEY_TO_ADD_NOTE';

export const LABELS_LABELKEYS = 'LABELS_LABELKEYS';